Repository WFCD/warframe-hub, pull requests merged in 2019-06, with the labels that each got.

#305 safer nightwave check
  src/components/panels/NightwavePanel.vue
  src/store.js
Labels: Scope: Core, Severity4: Inconvenient, Type: Bug

#317 start using a common travis status script
  .github/travis/fail.sh
  .github/travis/success.sh
  .travis.yml
Labels: Scope: CI, Severity3: Minor, Type: Maintenance, Type: Refactor

#309 Collapse excess invasions, Fix #59
  .github/CONTRIBUTING.md
  src/assets/json/components.json
  src/components/Collapsible.vue
  src/components/Invasion.vue
  src/components/Spoiler.vue
  src/components/panels/InvasionsPanel.vue
  src/store.js
Labels: Scope: Core, Type: Feature Request

#316 add workbox configs to skip waiting
  vue.config.js
Labels: Scope: Core, Severity4: Inconvenient, Type: Bug

#314 in-app notifications
  package-lock.json
  package.json
  src/App.vue
  src/Notifier.js
  src/components/modalDialogs/FissureFilters.vue
  src/components/modalDialogs/NotificationFilters.vue
  src/components/modalDialogs/Settings.vue
  src/components/modalDialogs/SoundFilters.vue
  src/main.js
Labels: Scope: Core, Type: Feature Request

#313 News Refactor pt2
  src/assets/json/components.json
  src/components/panels/NewsPanel.vue
  src/store.js
Labels: Scope: Core, Type: Feature Request, Type: Refactor

#322 Add missing routing for rivens data
  src/router.js
Labels: Scope: Core, Severity3: Minor, Type: Bug

#323 clean up badges
  README.md
Labels: Scope: Documentation, Type: Refactor
