Repository WFCD/warframe-hub, pull requests merged in 2019-05, with the labels that each got.

#292 Fix negative daily reset timer
  src/components/panels/ResetPanel.vue
Labels: Scope: Core, Severity2: Major, Type: Bug, vue

#297 drop animation on invasions
  src/components/panels/InvasionsPanel.vue
Labels: Scope: Core, Severity4: Inconvenient, Type: Refactor

#298 switch over to our caravaggio instance
  src/components/panels/NewsPanel.vue
Labels: Scope: Core, Severity4: Inconvenient, Type: Refactor

#299 fix some badges
  .github/ISSUE_TEMPLATE.md
  README.md
Labels: Scope: Documentation, Severity4: Inconvenient, Type: Refactor

#301 Revamp News Component & other tweaks
  src/assets/less/common.less
  src/components/DropdownNavItem.vue
  src/components/Navbar.vue
  src/components/NoDataItem.vue
  src/components/TimeBadge.vue
  src/components/panels/AcolytesPanel.vue
  src/components/panels/NewsPanel.vue
  src/components/panels/SortiePanel.vue
  src/components/panels/VoidTraderPanel.vue
Labels: Scope: Core, Severity3: Minor, Type: Enhancement, Type: Feature Request, Type: Refactor

#302 Slim down news component
  src/components/panels/NewsPanel.vue
Labels: Type: Refactor

#300 Add old-hub Project Link
  src/components/Navbar.vue
Labels: Scope: Core, Type: Feature Request
