Repository WFCD/warframe-hub, pull requests merged in 2019-09, with the labels that each got.

#355 drop extra travis status stuff
  .travis.yml
Labels: Type: Maintenance

#354 Clean up PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Scope: Documentation, Type: Maintenance

#353 Sentry migration
  package-lock.json
  package.json
  src/main.js
Labels: Type: Maintenance

#350 Added "Night Compact" theme
  src/App.vue
  src/assets/json/themes.json
  src/assets/less/common.less
  src/assets/less/compact.less
  src/components/Invasion.vue
  src/components/panels/AcolytesPanel.vue
  src/components/panels/AlertPanel.vue
  src/components/panels/BountyPanel.vue
  src/components/panels/ConstructionPanel.vue
  src/components/panels/DarvoDealsPanel.vue
  src/components/panels/EventsPanel.vue
  src/components/panels/FissuresPanel.vue
  src/components/panels/InvasionsPanel.vue
  src/components/panels/NightwavePanel.vue
  src/components/panels/ResetPanel.vue
  src/components/panels/SalesPanel.vue
  src/components/panels/SortiePanel.vue
  src/components/panels/TimePanel.vue
  src/components/panels/VoidTraderPanel.vue
  src/main.js
  src/views/Timer.vue
Labels: Scope: Core, Severity3: Minor, Type: Enhancement, Type: Feature Request
