Repository WFCD/warframe-hub, pull requests merged in 2021-12, with the labels that each got.

#644 fix: more error filtering
  src/components/Invasion.vue
  src/components/NoDataItem.vue
  src/components/panels/EventsPanel.vue
  src/components/panels/TimePanel.vue
  src/main.js
  src/store.js
  src/views/Timer.vue
Labels: Severity3: Minor, Type: Maintenance, Scope: Core, Status: Awaiting Review

#648 fix: baro timer not counting properly
  package.json
  src/components/TimeBadge.vue
Labels: Type: Bug, Status: Awaiting Review, Scope: Data Representation

#645 feat: leverage vuex modules
  src/App.vue
  src/Notifier.js
  src/components/modalDialogs/FissureFilters.vue
  src/components/modalDialogs/Languages.vue
  src/components/modalDialogs/NotificationFilters.vue
  src/components/modalDialogs/Platforms.vue
  src/components/modalDialogs/Settings.vue
  src/components/modalDialogs/SoundFilters.vue
  src/components/panels/BountyPanel.vue
  src/components/panels/FissuresPanel.vue
  src/components/panels/InvasionsPanel.vue
  src/components/panels/NewsPanel.vue
  src/main.js
  src/store.js
  src/stores/cache.js
  src/stores/worldstate.js
  src/utilities.js
  src/views/Codex.vue
  src/views/RivenData.vue
  src/views/Synthesis.vue
  src/views/Timer.vue
Labels: Type: Enhancement, Type: Maintenance, Scope: Core, Status: Awaiting Review

#659 fix: map getters & wait a tick for params
  src/views/OpenWorld/Earth/Map.vue
  src/views/OpenWorld/Venus/Map.vue
Labels: Type: Bug, Severity2: Major, Scope: Documentation

#585 feat: Aggregate timer
  src/App.vue
  src/assets/json/components.json
  src/assets/less/coloration.less
  src/assets/less/common.less
  src/components/panels/AggregatedTimePanel.vue
  src/components/panels/ResetPanel.vue
  src/components/panels/SentientOutpostsPanel.vue
  src/lang/en.json
  src/mixins/update.js
  src/registerServiceWorker.js
  src/utilities.js
  src/views/Timer.vue
Labels: help wanted, Type: Enhancement, Status: In Progress
